kind: pipeline
name: checkups
workspace:
  base: /go
  path: src/github.com/cblomart/vsphere-graphite

clone:
  disable: true

steps:
  # restore from latest build
  - restore:
    name: restore
    image: cblomart/gobasebuild
    environment:
      MC_HOSTS_s3:
        from_secret: s3_host
    commands:
    - last=$(mc find s3/vsphere-graphite --regex "[0-9]+/workspace.tgz" --newer-than 3d | tail -1)
    - if [ ! -z "$last" ]; then mc cat $last | tar xzf - -C /; fi
  # clone from git
  - clone:
    name: clone
    image: plugins/git
    tags: true
  # check dependencies
  - dependancies:
    name: dependancies
    image: cblomart/gobasebuild
    environment:
      MC_HOSTS_s3:
        from_secret: s3_host
    commands:
    - go version
    - mc mb -p s3/vsphere-graphite
    - make godeps
    - go generate ./...
    - tar czf - /go | mc pipe s3/vsphere-graphite/$DRONE_BUILD_NUMBER/workspace.tgz
  # do the checkups
  - checkups:
    name: checks
    image: cblomart/gobasebuild
    commands:
    - make checks

---
kind: pipeline
name: build-linux
workspace:
  base: /go
  path: src/github.com/cblomart/vsphere-graphite

clone:
  disable: true

steps:
  - restore:
    name: restore
    image: cblomart/gobasebuild
    environment:
      MC_HOSTS_s3:
        from_secret: s3_host
    commands:
    - mc cat s3/vsphere-graphite/$DRONE_BUILD_NUMBER/workspace.tgz | tar xzf - -C /
  - build:
    name: build
    image: cblomart/gobasebuild
    commands:
    - make build-linux-amd64
  - upx:
    name: upx
    image: cblomart/gobasebuild
    commands:
    - make upx-linux-amd64
    when:
      event: [ tag ]
  - push:
    name: push
    image: cblomart/gobasebuild
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
    volumes:
    - name: docker
      path: /var/run/docker.sock
    commands:
    - make docker-linux-amd64
    - docker login -u cblomart -p $DOCKER_PASSWORD
    - make push-linux-amd64
  - pack:
    name: pack
    image: cblomart/gobasebuild
    commands:
    - make dist-linux-amd64
    - cp /tmp/vsphere-graphite_*.tgz releases/
    when:
      event: [ tag ]
  - release:
    name: release
    image: plugins/github-release
    environment:
      GIHUB_SECRET:
        from_secret: github_secret
    files:
      - releases/*.tgz
    checksum:
      - sha256
    when:
      event: [ tag ]  

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

depends_on:
  - checkups

---
kind: pipeline
name: build-arm
workspace:
  base: /go
  path: src/github.com/cblomart/vsphere-graphite

clone:
  disable: true

steps:
  - restore:
    name: restore
    image: cblomart/gobasebuild
    environment:
      MC_HOSTS_s3:
        from_secret: s3_host
    commands:
    - mc cat s3/vsphere-graphite/$DRONE_BUILD_NUMBER/workspace.tgz | tar xzf - -C /
  - build:
    name: build
    image: cblomart/gobasebuild
    commands:
    - make build-linux-arm
  - upx:
    name: upx
    image: cblomart/gobasebuild
    commands:
    - make upx-linux-arm
  - push:
    name: push
    image: cblomart/gobasebuild
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
    volumes:
    - name: docker
      path: /var/run/docker.sock
    commands:
    - make docker-linux-arm
    - docker login -u cblomart -p $DOCKER_PASSWORD
    - make push-linux-arm
  - pack:
    name: pack
    image: cblomart/gobasebuild
    commands:
    - make dist-linux-arm
    - cp /tmp/vsphere-graphite_*.tgz releases/
  - release:
    name: release
    image: plugins/github-release
    environment:
      GIHUB_SECRET:
        from_secret: github_secret
    files:
      - releases/*.tgz
    checksum:
      - sha256

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

trigger:
  event: [ tag ]

depends_on:
  - checkups

---
kind: pipeline
name: build-windows
workspace:
  base: /go
  path: src/github.com/cblomart/vsphere-graphite

clone:
  disable: true

steps:
  - restore:
    name: restore
    image: cblomart/gobasebuild
    environment:
      MC_HOSTS_s3:
        from_secret: s3_host
    commands:
    - mc cat s3/vsphere-graphite/$DRONE_BUILD_NUMBER/workspace.tgz | tar xzf - -C /
  - build:
    name: build
    image: cblomart/gobasebuild
    commands:
    - make build-windows-amd64
  - upx:
    name: upx
    image: cblomart/gobasebuild
    commands:
    - make upx-windows-amd64
  - pack:
    name: pack
    image: cblomart/gobasebuild
    commands:
    - make dist-windows-amd64
    - cp /tmp/vsphere-graphite_*.tgz releases/
  - release:
    name: release
    image: plugins/github-release
    environment:
      GIHUB_SECRET:
        from_secret: github_secret
    files:
      - releases/*.tgz
    checksum:
      - sha256

trigger:
  event: [ tag ]

depends_on:
  - checkups

---
kind: pipeline
name: build-darwin
workspace:
  base: /go
  path: src/github.com/cblomart/vsphere-graphite

clone:
  disable: true

steps:
  - restore:
    name: restore
    image: cblomart/gobasebuild
    environment:
      MC_HOSTS_s3:
        from_secret: s3_host
    commands:
    - mc cat s3/vsphere-graphite/$DRONE_BUILD_NUMBER/workspace.tgz | tar xzf - -C /
  - build:
    name: build
    image: cblomart/gobasebuild
    commands:
    - make build-darwin-amd64
  - upx:
    name: upx
    image: cblomart/gobasebuild
    commands:
    - make upx-darwin-amd64
  - pack:
    name: pack
    image: cblomart/gobasebuild
    commands:
    - make dist-darwin-amd64
    - cp /tmp/vsphere-graphite_*.tgz releases/
    when:
      event: [ tag ]
  - release:
    name: release
    image: plugins/github-release
    environment:
      GIHUB_SECRET:
        from_secret: github_secret
    files:
      - releases/*.tgz
    checksum:
      - sha256

trigger:
  event: [ tag ]

depends_on:
  - checkups

---
kind: pipeline
name: cleanup
workspace:
  base: /go
  path: src/github.com/cblomart/vsphere-graphite

clone:
  disable: true

steps:
  - cleanup:
    name: cleanup
    image: cblomart/gobasebuild
    environment:
      MC_HOSTS_s3:
        from_secret: s3_host
    commands:
    - mc rm -r --force --older-than 3d s3/vsphere-graphite 

trigger:
  status:
  - success
  - failure